//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&ScalingAdvisorConfiguration{}, func(obj interface{}) {
		SetObjectDefaults_ScalingAdvisorConfiguration(obj.(*ScalingAdvisorConfiguration))
	})
	return nil
}

func SetObjectDefaults_ScalingAdvisorConfiguration(in *ScalingAdvisorConfiguration) {
	SetDefaults_ClientConnectionConfiguration(&in.ClientConnection)
	SetDefaults_LeaderElectionConfiguration(&in.LeaderElection)
	SetDefaults_ServerConfig(&in.Server)
}
