// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package constants

const (
	// OperatorName is the name of the scalingadvisor operator.
	OperatorName = "scalingadvisor"
	// OperatorConfigGroupName is the group name for OperatorConfiguration
	OperatorConfigGroupName = "config.sa.gardener.cloud"
	// OperatorGroupName is the name of the group for all scaling recommender custom resources.
	OperatorGroupName = "sa.gardener.cloud"
)

const (
	// KindScalingAdvisorConfiguration is the KIND for scaling advisor configuration.
	KindScalingAdvisorConfiguration = "ScalingAdvisorConfiguration"
	// KindClusterScalingAdvice is the KIND for ClusterScalingAdvice generated by the scaling-advisor operator.
	KindClusterScalingAdvice = "ClusterScalingAdvice"
	// KindClusterScalingConstraint is the KIND for constraint object that is reconciled by the scaling-advisor operator in order to generate the scaling advice.
	KindClusterScalingConstraint = "ClusterScalingConstraint"
)

const (
	// AnnotationEnableScalingDiagnostics is the annotation key to enable scaling diagnostics for a cluster.
	// This is applied by a user/tool on the ClusterScalingConstraint object which produces diagnostics withing
	// the generated ClusterScalingAdvice.Status.
	AnnotationEnableScalingDiagnostics = "sa.gardener.cloud/enable-scaling-diagnostics"
)

const (
	// LabelSimulationID is the label key to identify simulation objects for a specific simulation run.
	// The value of the label is the simulation ID.
	LabelSimulationID = "sa.gardener.cloud/simulation-id"
)

const (
	DefaultMinKAPIPort             = 8084
	DefaultOperatorServerPort      = 8085
	DefaultOperatorHealthProbePort = 8086
	DefaultOperatorMetricsPort     = 8087
	DefaultOperatorProfilingPort   = 8088
)
