// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

package constants

const (
	// OperatorName is the name of the scalingadvisor operator.
	OperatorName = "scalingadvisor"
	// OperatorConfigGroupName is the group name for OperatorConfiguration
	OperatorConfigGroupName = "config.sa.gardener.cloud"
	// OperatorGroupName is the name of the group for all scaling recommender custom resources.
	OperatorGroupName = "sa.gardener.cloud"
)

const (
	// KindScalingAdvisorConfiguration is the KIND for scaling advisor configuration.
	KindScalingAdvisorConfiguration = "ScalingAdvisorConfiguration"
	// KindClusterScalingAdvice is the KIND for ClusterScalingAdvice generated by the scaling-advisor operator.
	KindClusterScalingAdvice = "ClusterScalingAdvice"
	// KindClusterScalingConstraint is the KIND for constraint object that is reconciled by the scaling-advisor operator in order to generate the scaling advice.
	KindClusterScalingConstraint = "ClusterScalingConstraint"
)
