# Force neutral theme and override the text color token (N1 -> black)
vars: {
  d2-config: {
    theme-id: 103
    theme-overrides: {
       N2: "#000000"
    }
  }
}
mcm: {
  label: Machine Controller Manager \n (Lifecycle Controller)
  icon: sliders.svg
  width: 60
  height: 60
}
scadop: {
  label: Scaling Advisor Operator \n (Advisory Controller)
  #icon.near: center-left
#  icon.near: top-center
#  label.near: bottom-center
 icon: map.svg
  width: 60
  height: 60
}

ascontrol: {
  label: API Server \n (control cluster)
  icon: server.svg
  shape: image
  width: 60
  height: 60
}

astarget: {
  label : API Server \n (target cluster)
  icon: server.svg
  shape: image
  width: 60
  height: 60
}

cp: Cloud Provider
cp.shape: cloud

astarget --> mcm: 8. Derive ClusterScalingFeedback
astarget --> scadop: 3. Derive ClusterSnapshot \n (Nodes, Pods, etc)
mcm --> ascontrol: 1. Provide ClusterScalingConstraint \n and ClusterScalingFeedback 
ascontrol --> scadop: 2. Consume  ClusterScalingConstraint \n and ClusterScalingFeedback 
scadop --> ascontrol: 4. Provide ScalingAdvice


ascontrol --> mcm: 5. Consume ScalingAdvice
mcm --> cp: 6. Follow ScalingAdvice \n and Add/Remove Instances
cp --> astarget: 7. Register New Nodes \n and/or ResourceExhaustion for Instances
